#!/bin/bash -e

set -e -o pipefail

CURDIR="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"

source "$CURDIR/lib/base.bash"
source "$CURDIR/lib/check.bash"
source "$CURDIR/lib/parse.bash"

print_usage() {
cat << EOF
Usage: $0 [-s stage] <recipe-path>
  -s stage      : Specify the execution stage.
                  Valid values are: 'build', or 'image'.
                  If not specified, all stages will be executed.
  <recipe-path> : Path to the recipe file.

Available recipe files in this workspace:
EOF
    compgen -f "$CURDIR/sequence/"
}

PACKAGES_TO_BUILD=()

parse_recipe_file() {
    while read -r line; do
        if [[ "$line" =~ ^[[:space:]]*# ]] || [[ -z "$line" ]]; then
            continue
        fi
        PACKAGES_TO_BUILD+=("$line")
    done < "$1"
}

STAGE=""
while getopts ":s:" opt; do
    case $opt in
        s)
            STAGE="$OPTARG"
            ;;
        *)
            print_usage
            exit 1
            ;;
    esac
done
shift $((OPTIND - 1))

if [ "$#" -ne 1 ]; then
    print_usage
    exit 1
fi

# Basic sanity checks
check_vpkg_git

parse_recipe_file "$1"

if [[ "$STAGE" == "build" ]] || [[ -z "$STAGE" ]]; then
    source "$CURDIR/lib/fetch.bash"
    source "$CURDIR/lib/build.bash"

    for ((idx=0; idx<${#PACKAGES_TO_BUILD[@]}; idx++)); do
        PKGNAME="${PACKAGES_TO_BUILD[$idx]}"
        abinfo "[$PKGNAME $((idx+1))/${#PACKAGES_TO_BUILD[@]}] Building package ..."
        set_title "[$((idx+1))/${#PACKAGES_TO_BUILD[@]}] ${PKGNAME}"
        ( build_one_package "$CURDIR/packages/$PKGNAME" "$CURDIR/sources" "$CURDIR/build" "$CURDIR/stage" );
    done

    abinfo "BUILD SUCCESSFUL"
fi


if [[ "$STAGE" == "image" ]] || [[ -z "$STAGE" ]]; then
    # layout and install to image
    source "$CURDIR/lib/assemble.bash"
    IMAGE_NAME="$(basename "$1").img"
    MNT_POINT="$(mktemp -d)"
    BOOT_SECT_FILE=''
    IS_BOOT_DISK=0
    if [[ "${PACKAGES_TO_BUILD[*]}" =~ "freedos-boot" ]]; then
        IS_BOOT_DISK=1
    fi
    rm -fv "$CURDIR/$IMAGE_NAME"
    create_blank_floppy_image "$CURDIR/$IMAGE_NAME" $((1440 * 1024))
    mount_floppy_image "$CURDIR/$IMAGE_NAME" "$MNT_POINT"
    for ((idx=0; idx<${#PACKAGES_TO_BUILD[@]}; idx++)); do
        PKGNAME="${PACKAGES_TO_BUILD[$idx]}"
        PKG_SLUG="$(get_package_slug "$CURDIR/packages/$PKGNAME" true)"
        abinfo "[$PKGNAME $((idx+1))/${#PACKAGES_TO_BUILD[@]}] Installing files to floppy image ..."
        if [[ "$PKGNAME" == "freedos-boot" ]]; then
            BOOT_SECT_FILE="$CURDIR/stage/$PKG_SLUG/boot.bin"
            if [[ ! -f "$BOOT_SECT_FILE" ]]; then
                abdie "Boot sector file '$BOOT_SECT_FILE' not found. Cannot create bootable floppy image."
            fi
            continue
        fi
        install_files_to_floppy "$CURDIR/stage/$PKG_SLUG" "$MNT_POINT" "$IS_BOOT_DISK"
    done
    unmount_floppy_image "$MNT_POINT" "$CURDIR/$IMAGE_NAME"
    if [[ "$IS_BOOT_DISK" -eq 1 ]]; then
        abinfo "Inserting boot sector into floppy image ..."
        insert_boot_section_image "$CURDIR/$IMAGE_NAME" "$BOOT_SECT_FILE"
    fi

    abinfo "IMAGE CREATION SUCCESSFUL: $CURDIR/$IMAGE_NAME"
fi

set_title ""
