@echo off

SET DOSDRV=%_CWD%
for %%i in ( A B C D E F G H I J K L M N O P Q R S T U V W X Y Z ) do if "%_CWD%" == "%%i:\" set DOSDRV=%%i:

SET DOSDIR=%DOSDRV%\FREEDOS
rem SET COMSPEC=%dosdir%\BIN\COMMAND.COM
SET PATH=%dosdir%\BIN;%dosdir%\LINKS

SET OS_NAME=FreeDOS
SET OS_VERSION=1.4
SET CFGPATH=
SET AUTOFILE=%DOSDRV%\FDAUTO.BAT
SET CFGFILE=%DOSDRV%\FDCONFIG.SYS

SHSUCDX.COM /D:MSCD000
